name: pl-template
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.10.0=py38h32f6830_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h1e8a9f7_1000
  - ca-certificates=2020.12.5=h5b45459_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py38haa244fe_0
  - cffi=1.14.1=py38hba49e27_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.1=py38hba49e27_0
  - cudatoolkit=10.2.89=h74a9793_1
  - freetype=2.10.2=hd328e21_0
  - fsspec=0.8.4=py_0
  - future=0.18.2=py38h32f6830_1
  - google-auth=1.21.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.31.0=py38h735fc1f_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2020.1=216
  - joblib=0.16.0=py_0
  - jpeg=9d=he774522_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libpng=1.6.37=ha81a0f5_2
  - libprotobuf=3.13.0=h200bbdf_0
  - libtiff=4.1.0=h885aae3_6
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.2=h62dcd97_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.2.2=py_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py38hb782905_0
  - more-itertools=8.6.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.1=h7ef1ec2_1
  - numpy=1.19.1=py38h72c728b_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pillow=7.2.0=py38h7011068_1
  - pip=20.2.2=py_0
  - pluggy=0.13.1=py38h9bdc248_3
  - protobuf=3.13.0=py38h7ae7562_0
  - py=1.9.0=pyh9f0ad1d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytest=6.1.2=py38haa244fe_0
  - python=3.8.5=h60c2a47_7_cpython
  - python_abi=3.8=1_cp38
  - pytorch=1.7.0=py3.8_cuda102_cudnn7_0
  - pytorch-lightning=1.0.8=pyhd8ed1ab_0
  - pyyaml=5.3.1=py38h9de7a3e_0
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-learn=0.23.2=py38hf00eced_0
  - scipy=1.5.0=py38h9439919_0
  - setuptools=49.6.0=py38h32f6830_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=he774522_0
  - tensorboard=2.2.0=py_0
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=he774522_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=0.7.0=py38
  - torchvision=0.8.1=py38_cu102
  - tqdm=4.48.2=pyh9f0ad1d_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.10=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - win_inet_pton=1.1.0=py38_0
  - wincertstore=0.2=py38_1003
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h62dcd97_1009
  - zstd=1.4.5=h1f3a1b7_2
  - pip:
      - antlr4-python3-runtime==4.8
      - configparser==5.0.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.5
      - gitpython==3.1.8
      - hydra-core==1.0.0
      - importlib-resources==3.0.0
      - omegaconf==2.0.1
      - pathtools==0.1.2
      - promise==2.3
      - psutil==5.7.2
      - python-dateutil==2.8.1
      - sentry-sdk==0.17.5
      - shortuuid==1.0.1
      - smmap==3.0.4
      - subprocess32==3.5.4
      - wandb==0.10.12
      - watchdog==0.10.3

