name: pl-template
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.0.3
  - pytorch=1.10.2
  - cudatoolkit=11.3
  - pytorch-lightning=1.5.10
  - scikit-learn=0.24.2
  - pip:
      - hydra-core==1.1.1
      - wandb==0.12.10